name: terraform
on:
  workflow_dispatch:

jobs:
  terraform_plan:
    runs-on: ubuntu-latest
    steps:
    - uses: hashicorp/setup-terraform@v2
      name: Setup Terraform
      with:
        terraform_version: "1.6.3"
        terraform_wrapper: false
    - name: Terraform Init
      run: terraform init
    - name: Terraform Plan
      run: terraform plan
